name: slow_net_simulator
description: "A Flutter package to simulate different network conditions for testing purposes.
author: osama yeslam (os7soft)
homepage: https://github.com/OS7-SOFT/slow_net_simulator"

version: 1.0.0
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
